[tool.poetry]
name = "iitp-python"
version = "0.1.0"
description = "Code for the iitp python course"
authors = ["Danitim <danitim4@gmail.com>"]
license = "Unlicense"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
